[package]
name = "rust-hello-world"
version = "0.0.1"
authors = ["Alexander Slesarev <alex.slesarev@gmail.com>"]

[dependencies]
regex = "0.1.44"
lazy_static = "0.1.15"
futures = "0.1.14"
hyper = "0.11.2"
